#pragma once

inline enum {
    DVAL_INT,
    DVAL_BYTE,
    DVAL_CHAR,
    DVAL_SHORT,
    DVAL_LONG,
    DVAL_FLOAT,
    DVAL_BOOL,
    DVAL_STR,
    DVAL_FUN,
    DVAL_ERR,
    DVAL_SYM,
    DVAL_PACK,
    DVAL_IMPORT,
    DVAL_OP,
    DVAL_BODY,
    DVAL_PACKAGE
} DVAL_TYPE;

inline enum {
    DERR_DIV_BY_ZERO,
    DERR_INVALID_OPERATOR,
    DERR_INVALID_NUMBER,
    DERR_INVALID_FUNCTION,
    DERR_INVALID_ARGUMENTS,
    DERR_INVALID_SYMBOL,
    DERR_INVALID_ASSIGNMENT,
    DERR_INVALID_EXPRESSION,
    DERR_INVALID_PARAMETERS,
    DERR_INVALID_RETURN,
    DERR_INVALID_RETURN_TYPE,
} DERR_TYPE;


enum {
    MUTABLE,
    IMMUTABLE,

    NULLABLE,
    NON_NULLABLE
};
