#pragma once
#include <functional>

inline enum {
    DVAL_INT,
    DVAL_BYTE,
    DVAL_CHAR,
    DVAL_SHORT,
    DVAL_LONG,
    DVAL_FLOAT,
    DVAL_BOOL,
    DVAL_STR,

    DVAL_INT_ARR,
    DVAL_BYTE_ARR,
    DVAL_CHAR_ARR,
    DVAL_SHORT_ARR,
    DVAL_LONG_ARR,
    DVAL_FLOAT_ARR,
    DVAL_BOOL_ARR,
    DVAL_STR_ARR,
    DVAL_FUN,
    DVAL_ERR,
    DVAL_IDENT,
    DVAL_IDENT_ARR,
    DVAL_PACK,
    DVAL_IMPORT,
    DVAL_OP,
    DVAL_BODY,
    DVAL_PACKAGE
} DVAL_TYPE;

inline enum {
    DERR_DIV_BY_ZERO,
    DERR_INVALID_OPERATOR,
    DERR_INVALID_NUMBER,
    DERR_INVALID_FUNCTION,
    DERR_INVALID_ARGUMENTS,
    DERR_INVALID_SYMBOL,
    DERR_INVALID_ASSIGNMENT,
    DERR_INVALID_EXPRESSION,
    DERR_INVALID_PARAMETERS,
    DERR_INVALID_RETURN,
    DERR_INVALID_RETURN_TYPE,
} DERR_TYPE;


enum {
    MUTABLE = 0,
    IMMUTABLE = 1,

    NULLABLE = 2,
    NON_NULLABLE = 3,
};
