#pragma once

inline enum {
    DVAL_INT,
    DVAL_BYTE,
    DVAL_CHAR,
    DVAL_SHORT,
    DVAL_LONG,
    DVAL_FLOAT,
    DVAL_BOOL,
    DVAL_STR,

    DVAL_INT_ARR,
    DVAL_BYTE_ARR,
    DVAL_CHAR_ARR,
    DVAL_SHORT_ARR,
    DVAL_LONG_ARR,
    DVAL_FLOAT_ARR,
    DVAL_BOOL_ARR,
    DVAL_STR_ARR,
    DVAL_FUN,
    DVAL_ERR,
    DVAL_IDENT,
    DVAL_IDENT_ARR,
    DVAL_PACK,
    DVAL_IMPORT,
    DVAL_OP,
    DVAL_BODY,
    DVAL_PACKAGE,

    DVAL_FUN_BODY,
    DVAL_IDENT_CALL,
    DVAL_FUN_BLOCK,
    DVAL_FUN_ARGS,
    DVAL_FUN_RETURN,

    DVAL_NATIVE_VAR,
    DVAL_NATIVE_FUN
} DVAL_TYPE;


# define DVAL_NATIVE_TYPE_THREAD "thread"
#define DVAL_NATIVE_FUN_START_THREAD "__start_thread"
#define DVAL_NATIVE_FUN_ADD "__add"
#define DVAL_NATIVE_FUN_SUB "__sub"
#define DVAL_NATIVE_FUN_MUL "__mul"
#define DVAL_NATIVE_FUN_DIV "__div"
#define DVAL_NATIVE_FUN_MOD "__mod"
#define DVAL_NATIVE_FUN_AND "__and"
#define DVAL_NATIVE_FUN_EQ "__eq"
#define DVAL_NATIVE_FUN_GT "__gt"
#define DVAL_NATIVE_FUN_GTE "__gte"
#define DVAL_NATIVE_FUN_LT "__lt"
#define DVAL_NATIVE_FUN_LTE "__lte"
#define DVAL_NATIVE_FUN_NEQ "__neq"
#define DVAL_NATIVE_FUN_OR "__or"
#define DVAL_NATIVE_FUN_XOR "__xor"
#define DVAL_NATIVE_FUN_LSHIFT "__lshift"
#define DVAL_NATIVE_FUN_RSHIFT "__rshift"
#define DVAL_NATIVE_FUN_URSHIFT "__urshift"

inline enum {
    DERR_DIV_BY_ZERO,
    DERR_INVALID_OPERATOR,
    DERR_INVALID_NUMBER,
    DERR_INVALID_FUNCTION,
    DERR_INVALID_ARGUMENTS,
    DERR_INVALID_SYMBOL,
    DERR_INVALID_ASSIGNMENT,
    DERR_INVALID_EXPRESSION,
    DERR_INVALID_PARAMETERS,
    DERR_INVALID_RETURN,
    DERR_INVALID_RETURN_TYPE,
} DERR_TYPE;


enum {
    MUTABLE = 0,
    IMMUTABLE = 1,

    NULLABLE = 2,
    NON_NULLABLE = 3,
};
